### ISSUE TITLE
Code improvement: allow arbitrary input file domain formatting

### ISSUE THREAD

**Issue by harleo** [harleo/blink#3]
I'm looking for some(one) to add code to allow arbitrary input file domain formatting.
The user should be allowed to use URLs containing: with HTTP(S)/without HTTP(s)/line by line/separated by comma etc. thus it shouldn't matter how it is formatted for parsing.

Make sure to edit the "Format" section in the README according to your changes as well.

If you'd like to help, please comment below and make a pull request.

Thanks :)

**Comment by harleo** [comment]
@TacoBirb 
What I meant was URL parsing from a file like such: `acme.com, google.com, bing.com` - it shouldn't matter to the parser whether it is line by line or separated by commas.

**Comment by TacoBirb** [comment]
I'll see what I can do - anything for a t-shirt right :P
