### ISSUE TITLE
Project improvement: add missing pipfile code dependencies

### ISSUE THREAD

**Issue by harleo** [harleo/blink#4]
I think the Pipfile is missing dependencies to run.
Please add those to resolve potentially missing libraries and make a pull request.

Thanks :)

**Comment by pranaysahith** [comment]
I see the Pipfile has dependencies listed and I am able run the code. what modules/libraries do you think are missing?

**Comment by harleo** [comment]
Hey @pranaysahith 
I just wasn't quite sure if all dependencies are included to run.
If you're able to run the code out of the box with the Pipfile dep. then it's fine :)
